### PR TITLE
Migration to iced 0.10

### PR DESCRIPTION
**Pull request by GyulyVGC**
Hey, there we go again.

This time the update is pretty big and lots of things has changed.
I started migrating but I'm currently stuck in some problems related to the new available renderers.

If you can give it a look it'd be really nice.
Thanks in advance!

### CODE REVIEW

**Comment by Joylei** [comment]
Iced changes a lot.  Make it work again.

**Comment by GyulyVGC** [comment]
> Iced changes a lot. Make it work again.

Amazing, tyvm.
I saw a TODO in the code about text rotation. This is just to inform you that I think now it's possible to rotate text using the Advanced strategy (which should not be used for other tasks though since it's less efficient)

**Comment by Joylei** [comment]
OK, let me try the text Advanced strategy.

**Comment by Joylei** [comment]
Tried. But text rotation is still not supported.

**Comment by GyulyVGC** [comment]
Maybe it's supported only for canvas? https://github.com/iced-rs/iced/pull/1610

**Review by GyulyVGC — COMMENTED** [review]
Anyway, I've tried all the examples and everything looks good!

**Comment by GyulyVGC** [comment]
I did some more tests.

I found out that when using `tiny-skia` instead of `wgpu` the chart grids are not displayed at all.
I'm not sure if this is related to `plotters-iced` or is an upstream problem.

`tiny-skia` renderer can be tried disabling iced's default features.

**Comment by Joylei** [comment]
It seems line drawing does not work for iced tiny-skia.

**Comment by Joylei** [comment]
It turns out there's a mistake when processing colors in iced tiny-skia.

**Comment by GyulyVGC** [comment]
Damn.
After looking more accurately, could the following exact line be the root?

https://github.com/iced-rs/iced/blob/50ce65b3b7ad10a8537b751b3890d9dcfaecf846/core/src/rectangle.rs#L105

It reports:

```rs
if width > 0.0 && height > 0.0
```

instead of

```rs
if width > 0.0 || height > 0.0
```

Do you think there is a reason for this or we should open an issue? @Joylei

**Comment by Joylei** [comment]
Obviously there is something wrong. Go ahead to open an issue for canvas feature.

**Pull request merged**
